name: Build_and_deploy_API
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
    build-and-deploy:
        runs-on: [self-hosted]
        steps:
          - name: Checkout code
            uses: actions/checkout@v4 
          - name: Log into Docker Hub
            uses: docker/login-action@v1
            with: 
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Build image
            run: |
              docker build \
              -t ${{secrets.DOCKER_USERNAME}}/aaron-final-api:${{github.run_number}} \
              -t ${{secrets.DOCKER_USERNAME}}/aaron-final-api:latest \
                ./API/RecipieAPI/RecipieAPI/

          # ./API/RecipieAPI --configuration Release
          - name: Push image
            run: |
              docker push ${{secrets.DOCKER_USERNAME}}/aaron-final-api --all-tags
          - name: Deploy on Kube
            run: |
              export PATH=$PATH:~/.nix-profile/bin:/nix/profiles/default/bin
              export IMAGE_TAG=${{github.run_number}}
              export DOCKER_USER=${{secrets.DOCKER_USERNAME}}
              export DATABASE="${{secrets.DB_CONNECTION}}"
              for file in API_Kube/*; do
                cat "$file" | envsubst | kubectl apply -f -;
              done

            


